FROM redhat/ubi8-minimal:8.7-1107
RUN microdnf update && microdnf install ca-certificates git tar openssh curl perl python38 shadow-utils diffutils jq

ADD docker/scripts/* /usr/local/bin/
RUN chmod +x /usr/local/bin/chat_workflow_v2.sh

ENTRYPOINT ["/usr/local/bin/chat_workflow_v2.sh"]
